# Generated by Django 4.1.5 on 2023-02-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='film',
            new_name='genre',
        ),
    ]
