# Generated by Django 4.1.5 on 2023-02-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_rename_film_film_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
