# Generated by Django 4.1.5 on 2023-02-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_rename_genre_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genres',
        ),
    ]
